DATA:
  train_name: ytvis
  test_name: default
  train_split: 0
  test_split: default
  train_list: None
  every_frame: 5
  n_frames: 5
  data_root: /local/riemann/home/msiam/Youtube-VOS/
  class_mapping: None
  class_names_list: None
  val_list: None
  num_classes_tr: 31  # Counting background for training
  num_classes_val: 10
  use_split_coco: False
  workers: 4
  image_size: [241, 425]
  padding_label: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  scale_min: None
  scale_max: None
  rot_min: None
  rot_max: None
  augmentations: []

TRAIN:
  ckpt_path: checkpoints/
  resume_training: False
  batch_size: 6
  epochs: 10
  log_freq : 50
  visdom_port: -1
  visdom_env: ""
  debug: False
  save_models: True
  lr: 0.0025
  scale_lr: 1.0
  mixup: False
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: [40, 70]

MODEL:
  arch: resnet
  pretrained: True  # Means the backbone has been pre-trained
  bins: [1, 2, 3, 6]
  dropout: 0.1
  m_scale: False
  layers: 50
  bottleneck_dim: 512

EVALUATION:
  episodic_val: False
  temporal_episodic_val: 0
  batch_size_val: 10
  manual_seed: 2020
  ckpt_used: best
  smoothing: True
  eval_vc: False

VISUALIZATION:
  visu: False

CLASSIFIER:
  distance: cos
  temperature: 20.
  adapt_iter: 50
  FB_param_type: soft
  weights: [1.0, 'auto', 'auto', 'auto']  #  [0.5, 1.0, 0.1]
  cls_lr: 0.025
  FB_param_update: [10]
  scl_temperature: 0.1
  nviews: 2
  tloss_type: pos_steer_avg
  cls_visdom_freq: 5
  adap_kshot: False

DISTRIBUTED:
  gpus: [0]

WANDB:
  wandb_user: 'yvv'
  wandb_project: 'tfss'
  wandb_run_name: ''
