DATA:
  train_name: nminivspw
  test_name: default
  train_split: 0
  test_split: default
  train_list: lists/nminivspw_pascal/train.txt
  data_root: /local/riemann/home/msiam/VSPW_All_Parsed/VSPW_480p/data/
  val_list: lists/nminivspw_pascal/val.txt
  test_list: lists/nminivspw_pascal/test.txt
  num_classes_tr: 16  # Counting background for training
  num_classes_val: 5
  num_classes_test: 5
  use_split_coco: False
  workers: 4
  image_size: 417
  padding_label: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  scale_min: 0.5
  scale_max: 2.0
  rot_min: -10
  rot_max: 10
  augmentations: ['hor_flip', 'vert_flip', 'resize']
  sprtset_as_frames: False
  multi_rnd_sprt: False # Flag only used for YTVIS

TRAIN:
  ckpt_path: checkpoints/
  resume_training: False
  batch_size: 6
  epochs: 10 # > 200,000 iterations
  log_freq : 50
  visdom_port: -1
  visdom_env: ""
  debug: False
  save_models: True
  lr: 0.0025
  scale_lr: 1.0
  mixup: False
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: [40, 70]
  training_loss: 'ce'

MODEL:
  arch: resnet
  pretrained: True  # Means the backbone has been pre-trained
  bins: [1, 2, 3, 6]
  dropout: 0.1
  m_scale: False
  layers: 50
  bottleneck_dim: 512

EVALUATION:
  episodic_val: False
  temporal_episodic_val: 4 #0: None, 1: TAO, 2: VSPW, 3: YTVIS, 4: NMiniVSPW
  shot: 1
  random_shot: False
  norm_feat: True
  batch_size_val: 10
  manual_seed: 2020
  ckpt_used: best
  FB_param_noise: 0
  smoothing: True
  n_runs: 1
  save_oracle: False
  eval_vc: True
  test_num: 0
  vc_wins: [15]
  vc_size_th: 0
  selected_weights: []

VISUALIZATION:
  visu: False
  visu_keyframes: False
  vis_dir: /local/data0/plots/
  analysis_dir: 'analysis/'

CLASSIFIER:
  distance: cos
  temperature: 20.
  adapt_iter: 50
  FB_param_type: soft
  weights: [1.0, 'auto', 'auto', 'auto']  #  [0.5, 1.0, 0.1]
  cls_lr: 0.025
  FB_param_update: [10]
  scl_temperature: 0.1
  nviews: 2
  tloss_type: [temporal_repri, pos_neg_steer_avg]
  temporal_window: 3
  temporal_step: 1
  cls_visdom_freq: 5
  refine_keyframes_ftune: True
  refine_iter: 10
  refine_oracle: False

DISTRIBUTED:
  gpus: [0]
